services:
  backend:
    build: ./backend
    container_name: backend-app
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 3000
    depends_on:
      - mongo
    networks:
      - ex07-network

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - ex07-network

  mongo:
    image: mongo:4.2.0
    container_name: mongo-db
    volumes:
      - mongo_data:/data/db
    expose:
      - 27017
    networks:
      - ex07-network

networks:
  ex07-network:

volumes:
  mongo_data:
